/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.map.view;

import br.com.map.controller.VotacaoController;

/**
 *
 * @author leonardo
 */
public class VotacaoView extends javax.swing.JFrame {    

    private VotacaoController votacaoController;
    
    /**
     * Creates new form Votacao
     * @param votacaoController
     */
    public VotacaoView(VotacaoController votacaoController) {
        initComponents();
        this.votacaoController = votacaoController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButtonOp2 = new javax.swing.JButton();
        jButtonOp1 = new javax.swing.JButton();
        jButtonOp3 = new javax.swing.JButton();
        jButtonOp4 = new javax.swing.JButton();
        jButtonOp5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelVencedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Opção 1",  new Integer(0)},
                {"Opção 2",  new Integer(0)},
                {"Opção 3",  new Integer(0)},
                {"Opção 4",  new Integer(0)},
                {"Opção 5",  new Integer(0)}
            },
            new String [] {
                "Opção", "Votos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setEnabled(false);
        table.setFocusable(false);
        table.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(table);

        jButtonOp2.setText("Opção 2");
        jButtonOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOp2ActionPerformed(evt);
            }
        });

        jButtonOp1.setText("Opção 1");
        jButtonOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOp1ActionPerformed(evt);
            }
        });

        jButtonOp3.setText("Opção 3");
        jButtonOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOp3ActionPerformed(evt);
            }
        });

        jButtonOp4.setText("Opção 4");
        jButtonOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOp4ActionPerformed(evt);
            }
        });

        jButtonOp5.setText("Opção 5");
        jButtonOp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOp5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Vencedor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonOp1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonOp2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonOp3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonOp4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonOp5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVencedor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelVencedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOp1)
                    .addComponent(jButtonOp2)
                    .addComponent(jButtonOp3)
                    .addComponent(jButtonOp4)
                    .addComponent(jButtonOp5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOp2ActionPerformed
        int pontos = this.votacaoController.getPontos("Opção 2")+1;
        this.votacaoController.atualizarPontos("Opção 2", pontos);
        this.table.setValueAt(pontos, 1, 1);
        this.jLabelVencedor.setText(this.votacaoController.getVencedor());
    }//GEN-LAST:event_jButtonOp2ActionPerformed

    private void jButtonOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOp1ActionPerformed
        int pontos = this.votacaoController.getPontos("Opção 1")+1;
        this.votacaoController.atualizarPontos("Opção 1", pontos);
        this.table.setValueAt(pontos, 0, 1);
        this.jLabelVencedor.setText(this.votacaoController.getVencedor());
    }//GEN-LAST:event_jButtonOp1ActionPerformed

    private void jButtonOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOp3ActionPerformed
        int pontos = this.votacaoController.getPontos("Opção 3")+1;
        this.votacaoController.atualizarPontos("Opção 3", pontos);
        this.table.setValueAt(pontos, 2, 1);
        this.jLabelVencedor.setText(this.votacaoController.getVencedor());
    }//GEN-LAST:event_jButtonOp3ActionPerformed

    private void jButtonOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOp4ActionPerformed
        int pontos = this.votacaoController.getPontos("Opção 4")+1;
        this.votacaoController.atualizarPontos("Opção 4", pontos);
        this.table.setValueAt(pontos, 3, 1);
        this.jLabelVencedor.setText(this.votacaoController.getVencedor());
    }//GEN-LAST:event_jButtonOp4ActionPerformed

    private void jButtonOp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOp5ActionPerformed
        int pontos = this.votacaoController.getPontos("Opção 5")+1;
        this.votacaoController.atualizarPontos("Opção 5", pontos);
        this.table.setValueAt(pontos, 4, 1);
        this.jLabelVencedor.setText(this.votacaoController.getVencedor());
    }//GEN-LAST:event_jButtonOp5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOp1;
    private javax.swing.JButton jButtonOp2;
    private javax.swing.JButton jButtonOp3;
    private javax.swing.JButton jButtonOp4;
    private javax.swing.JButton jButtonOp5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelVencedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
