
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 11 00:42:31 GMT-03:00 2019
//----------------------------------------------------

package br.edu.fip.compiladores.minijava;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAVE_DIREITA = 24;
  public static final int ADICAO = 36;
  public static final int MULTIPLICACAO = 38;
  public static final int INT = 11;
  public static final int VIRGULA = 31;
  public static final int PONTO = 30;
  public static final int STATIC = 6;
  public static final int AND = 40;
  public static final int IGUAL = 32;
  public static final int COLCHETE_ESQUERDA = 25;
  public static final int CLASS = 3;
  public static final int NUM = 22;
  public static final int MAIN = 8;
  public static final int IF = 12;
  public static final int THIS = 19;
  public static final int IGUAL_IGUAL = 34;
  public static final int ID = 21;
  public static final int COLCHETE_DIREITA = 26;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 10;
  public static final int TRUE = 17;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int PARENTESES_ESQUERDA = 27;
  public static final int EXCLAMACAO_IGUAL = 35;
  public static final int EXCLAMACAO = 41;
  public static final int VOID = 7;
  public static final int DIVISAO = 39;
  public static final int ELSE = 13;
  public static final int SYSTEM_OUT_PRINTLN = 15;
  public static final int WHILE = 14;
  public static final int PARENTESES_DIREITA = 28;
  public static final int PUBLIC = 5;
  public static final int PONTO_E_VIRGULA = 29;
  public static final int EXTENDS = 4;
  public static final int CHAVE_ESQUERDA = 23;
  public static final int STRING = 9;
  public static final int MENOR_QUE = 33;
  public static final int FALSE = 18;
  public static final int SUBTRACAO = 37;
  public static final int LENGTH = 16;
}

